services:

  back-end:
    build: back-end
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252"


  front-end:
    build: front-end
    image: softy-pinko-front-end:task4
    ports:
      - "9000:9000"
    depends_on:
    - back-end